### ISSUE TITLE
Source of helpfiles?

### ISSUE THREAD

**Issue by pcav** [Seboon/AutomaticBackup#1]
Apparently the source of help files is missing, together with their conf.py and Makefile, .po etc. Please add these, probably the compiled version can be removed.
Cheers.

**Comment by Seboon** [comment]
Hi Paolo,
Thank you for your kindness. I've just added the missing files.
I deleted the "corrupted" plugin from https://plugins.qgis.org and re-uploaded the good one.
Best regards

**Comment by NyakudyaA** [comment]
@Seboon how different is this plugin from auto saver plugin. If they do the same thing maybe it’s worth while to collaborate on the functionality

**Comment by pcav** [comment]
Agreed, I would like to avoid duplication and promote cooperation. Please let us know.
Thanks.

**Comment by pcav** [comment]
BTW, @NyakudyaA better opening a different ticket for this.
