### ISSUE TITLE
Plugin colloboration

### ISSUE THREAD

**Issue by NyakudyaA** [Seboon/AutomaticBackup#2]
# Problem

The plugin https://plugins.qgis.org/plugins/autoSaver/ seems to offer the same functionality as this plugin. Perhaps you should collaborate with the author of this plugin and merge your functionality.

I would like to avoid duplication and promote cooperation. Please let us know.
Thanks.

**Comment by Seboon** [comment]
Hello,
I've contacted the autho, of the plugin https://plugins.qgis.org/plugins/autoSaver/, @enricofer, to know if it would be possible to do that.
Thank you for your kindness,
Best regards

**Comment by enricofer** [comment]
Hi all, I don't see any problem on having many autosaving plugins in the repesitory. Anyway I'm currently working on other tools and I have no plans on working on autosaver plugin for now and I could't work on merging other functionalities. But if @seboon want to work on this I would be happy to share the plugin with him.

**Comment by NyakudyaA** [comment]
> Hi all, I don't see any problem on having many autosaving plugins in the repesitory. Anyway I'm currently working on other tools and I have no plans on working on autosaver plugin for now and I could't work on merging other functionalities. But if @Seboon want to work on this I would be happy to share the plugin with him.

Hi, @enricofer If two plugins offer almost identical functionalities it is better to collaborate than having two methods running parallel against. Maybe @Seboon you could do a PR against Auto Saver plugin and enhance from what it currently does or as noted above you fork it and maintain it and have proper attribution.

**Comment by pcav** [comment]
Hi @Seboon @enricofer I tend to agree with @NyakudyaA here: any change of merging these useful works?
Cheers.

**Comment by NyakudyaA** [comment]
Hi @Seboon any update to this

**Comment by Seboon** [comment]
Hi @NyakudyaA , @pcav ,
Thank you for your feedback.
I've forked @enricofer 's plugin and send him a pull request. As it's the first time I do this kind of thing, I hope i've done everything needed...
Best regards,
S.Poudroux

**Comment by enricofer** [comment]
I'm having a look to PR https://github.com/enricofer/autoSaver/pull/13 and I think It's happening something strange. @Seboon is submitting a complete rewriting of the code trying to comply Qgis repository staff (@NyakudyaA  @pcav ) suggestions to improve collaboration between contributors.
I understand each point of view but we are reaching an odd result. Keep the old plugin name, replacing its code with the new one. This is not what I call "collaboration".  
I've not look deeply into @Seboon work, but It seem an original contribution in its complex that can't be easily merged. 
We have only 3 alternatives:
1) @Seboon put his work in the trashcan and rewrite some parts to be merged in @enricofer plugin
2) @enricofer retire his plugin from the repository to allow @Seboon plugin pubblication
3) @Seboon and @enricofer plugins cohabit happily in the repository

**Comment by NyakudyaA** [comment]
> I'm having a look to PR [enricofer/autoSaver#13](https://github.com/enricofer/autoSaver/pull/13) and I think It's happening something strange. @Seboon is submitting a complete rewriting of the code trying to comply Qgis repository staff (@NyakudyaA @pcav ) suggestions to improve collaboration between contributors.
> I understand each point of view but we are reaching an odd result. Keep the old plugin name, replacing its code with the new one. This is not what I call "collaboration".
> I've not look deeply into @Seboon work, but It seem an original contribution in its complex that can't be easily merged.
> We have only 3 alternatives:
> 
>     1. @Seboon put his work in the trashcan and rewrite some parts to be merged in @enricofer plugin
> 
>     2. @enricofer retire his plugin from the repository to allow @Seboon plugin pubblication
> 
>     3. @Seboon and @enricofer plugins cohabit happily in the repository

@enricofer cc @Seboon I think the point of the contribution came from the fact that these two plugins offer identical functionalities. So from my take the solution should have been 
* @Seboon  fork your work and add his magic to consolidate the plugin so that it can become a monster.
* A rewrite would be done maybe to have a new gui using the latest libraries etc but still maintain @enricofer code base as the starting template for the work.

* Another pain point to consider would be who would be maintaining the repository if the merger happens

If the above situation is unattainable then maybe point 3 becomes valid. An example of successful plugin collaboration is the qgis2web plugin when we used to have qgis2leaf and a corresponding plugin to export to open layers.

What's your take @pcav
