### ISSUE TITLE
Settings are not memorized

### ISSUE THREAD

**Issue by ChameleonScales** [Seboon/AutomaticBackup#4]
The plugin's settings go back to their default values every time I reopen Qgis, even if I save and reopen the same .qgz or .qgs file.
I don't know if it's intended but I think the settings should be preserved either per project or globally, similarly to the other backup plugin AutoSaver.

QGIS version : 3.18.3
AutomaticBackup version : 0.1
OS : Debian 10.9

**Comment by Seboon** [comment]
Hi @ChameleonScales ,
Thanks for reporting this which should be fixed now.
Best regards.

**Comment by ChameleonScales** [comment]
I confirm that it memorizes everything now. Thanks for the fix!
